monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "alsa_card.platform-soc_spf_core_platform_sound"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
